config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "pages#index"
  resources :lists, only: ["index", "show", "create", "new"] do
    resources :bookmarks, only: ["create", "new"]
  end
  resources :bookmarks, only: ["destroy"]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list

  validates :movie, uniqueness: { scope: :list }
  validates :comment, length: { minimum: 6 }
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks

  validates :name, uniqueness: true, presence: true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks

  validates :title, uniqueness: true, presence: true
  validates :overview, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  before_action :set_bookmark, only: [:destroy]
  before_action :set_list, only: [:new, :create]

  def new
    @bookmark = Bookmark.new
  end

  def create
    @bookmark = Bookmark.new(params_bookmarks)
    @bookmark.list = @list
    if @bookmark.save
      redirect_to list_path(@list)
    else
      render :new
    end
  end

  def destroy
    @bookmark.destroy
    redirect_to list_path(@bookmark.list)
  end

  private

  def params_bookmarks
    params.require(:bookmark).permit(:comment, :movie_id, :list_id)
  end

  def set_list
    @list = List.find(params[:list_id])
  end

  def set_bookmark
    @bookmark = Bookmark.find(params[:id])
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def index
    @lists = List.all
  end

  def show
    @list = List.find(params[:id])
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(params_lists)
    if @list.save
      redirect_to list_path(@list)
    else
      render :new
    end
  end

  private

  def params_lists
    params.require(:list).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/bookmarks/new.html.erb
<h1>Create a bookmark</h1>

<%= simple_form_for [@list, @bookmark] do |f| %>
  <%= f.input :comment %>
  <%= f.association :movie %>
  <%= f.button :submit %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsMovieWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= yield %>
  </body>
</html>

app/views/lists/index.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://images.unsplash.com/photo-1536440136628-849c177e76a1?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1925&q=80);">
  <div class="container">
    <h1>Save any kind of movies</h1>
    <p>Whether to watch it later or re-watch it</p>
    <%# <a class="btn btn-flat" href="#">Apply now</a> %>
  </div>
</div>

<div class="container py-5">
  <div class="d-flex align-items-center justify-content-between">
    <h3 class="mb-4">My lists</h3>
    <%= link_to "Add a list", new_list_path, class: "btn btn-flat" %>
  </div>
  <div class="row">
    <% @lists.each do |list| %>
        <div class="col-12 col-sm-6 col-md-4 mb-3">
          <%= link_to list_path(list), class: "text-decoration-none" do %>
            <div class="card-category" data-aos="zoom-in" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= list.image_url %>')">
            <%= list.name %>
            </div>
          <% end %>
        </div>
    <% end %>
  </div>
</div>

app/views/lists/new.html.erb
<h1>What list do you want to create ?</h1>
<div class="container">
  <%= simple_form_for @list do |f| %>
    <%= f.input :name, collection: ["Drame", "Comédie", "Amour", "Action", "Documentaire"] %>
    <%= f.input :image_url %>
    <%= f.button :submit %>
  <% end %>
</div>

app/views/lists/show.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url('<%= @list.image_url %>');">
  <div class="container">
    <h1><%= @list.name %></h1>
  </div>
</div>

<div class="container">
  <div class= "d-flex justify-content-between py-4">
    <h1><%= @list.name %></h1>
    <%= link_to "Add a movie", new_list_bookmark_path(@list), class: "btn btn-flat" %>
  </div>
  <div class="row d-flex py-3">
    <% @list.bookmarks.each do |bookmark| %>
      <div class="col-12 col-sm-6 mb-3">
        <div class="movie-card shadow">
          <%= image_tag bookmark.movie.poster_url, class: "movie-image" %>
          <div class="text-card d-flex flex-column">
            <div class="p-2">
              <strong><%= bookmark.movie.title %></strong> • <span><%= bookmark.movie.rating %></span>
              <i class="fa-solid fa-star"></i>
            </div>
            <div class="p-2">
              <%= bookmark.movie.overview %>
            </div>
            <div class="d-flex justify-content-around">
              <%= bookmark.comment %>
              <%= link_to 'Delete',
                              bookmark_path(bookmark),
                              method: :delete,
                              data: { confirm: "Are you sure?" }, class: "text-decoration-none" %>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>
  <%= link_to "Back to lists", lists_path, class: "btn btn-flat" %>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to lists_path, class: "navbar-brand" do %>
      <%= image_tag "logo.jpeg" %>
    <% end %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
          <li class="nav-item active">
            <%= link_to "My lists", lists_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "New list", new_list_path, class: "nav-link" %>
          </li>
          <!--li class="nav-item"-->
          <!--/li-->
      </ul>
    </div>
  </div>
</div>